### ISSUE TITLE
Missing style check patterns for some cases with newlines.

### ISSUE THREAD

**Issue by HyukjinKwon** [apache/incubator-predictionio#206]
It looks travis does not check the coding style. Due to this, it looks there are some inconsistency across all the codes.

For example, some files do not have a newline at the end, the newlines between classes are also inconsistent and the parameters in functions or classes are nits to read. This would harm readability.

**Comment by dszeto** [comment]
Travis runs `sbt scalastyle` (https://github.com/PredictionIO/PredictionIO/blob/develop/.travis.yml#L45), but perhaps the rules are not catching newlines. You are very welcome to contribute a fix. :)

**Comment by HyukjinKwon** [comment]
@dszeto oh, sorry I could not see that. Let me add some fixes If I have some time!

**Comment by HyukjinKwon** [comment]
Fixed in https://github.com/apache/incubator-predictionio/pull/219
