### ISSUE TITLE
Java 8 hard requirement not met by installer

### ISSUE THREAD

**Issue by zebraf1** [apache/incubator-predictionio#223]
Installer file https://install.prediction.io/install.sh includes this line:
`sudo apt-get install openjdk-7-jdk libgfortran3 -y`

Source: https://github.com/PredictionIO/PredictionIO/blob/develop/bin/install.sh#L97

Release notes for PredictionIO 0.9.6 clearly state that "Starting from 0.9.6, Java 8 is a hard requirement".

The installer should match these requirements.

**Comment by zebraf1** [comment]
I used vagrant to build my Prediction.io which comes with Java 7 by default and building a new app gives me this error
```
Exception in thread "main" java.lang.NoSuchMethodError: java.security.SecureRandom.getInstanceStrong()Ljava/security/SecureRandom;
	at io.prediction.data.storage.AccessKeys$class.generateKey(AccessKeys.scala:66)
```
getInstanceStrong was implemented in Java 8:
https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html
vs
https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html

**Comment by dszeto** [comment]
Thanks for reporting! We are working on it.

**Comment by zebraf1** [comment]
Created PR #247

**Comment by zebraf1** [comment]
Java 8 was installed for me after using your updated installer script
