### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by nilay-automatesmb** [apache/incubator-predictionio#252]
While building from source, we are getting following error: incubator-predictionio/data/src/main/scala/org/apache/predictionio/data/storage/AccessKeys.scala:66: value getInstanceStrong is not a member of object java.security.SecureRandom

**Comment by dszeto** [comment]
Are you using Java 8?

**Comment by nilay-automatesmb** [comment]
Just saw that there is already a request: https://github.com/apache/incubator-predictionio/pull/247

**Comment by nilay-automatesmb** [comment]
Works with java 8
