### ISSUE TITLE
pio train error

### ISSUE THREAD

**Issue by birdspring** [apache/incubator-predictionio#274]
"pio build" is successfully executed on my machine. But when I tried "pio train", an error occurred to me, the log is as follows:

[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(myapp1,None))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[WARN] [Utils] Your hostname, yang resolves to a loopback address: 127.0.1.1; using 192.168.137.118 instead (on interface wlan0)
[WARN] [Utils] Set SPARK_LOCAL_IP if you need to bind to another address
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@192.168.137.118:59618]
[WARN] [MetricsSystem] Using default name DAGScheduler for source because spark.app.id is not set.
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: org.template.recommendation.DataSource@41d16cc3
[INFO] [Engine$] Preparator: org.template.recommendation.Preparator@649f25f3
[INFO] [Engine$] AlgorithmList: List(org.template.recommendation.ALSAlgorithm@bf75b5c)
[INFO] [Engine$] Data sanity check is on.
[INFO] [Engine$] org.template.recommendation.TrainingData does not support data sanity check. Skipping check.
[INFO] [Engine$] org.template.recommendation.PreparedData does not support data sanity check. Skipping check.
[WARN] [BLAS] Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
[WARN] [BLAS] Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
[WARN] [LAPACK] Failed to load implementation from: com.github.fommil.netlib.NativeSystemLAPACK
[WARN] [LAPACK] Failed to load implementation from: com.github.fommil.netlib.NativeRefLAPACK
[ERROR] [Executor] Exception in task 0.0 in stage 44.0 (TID 152)
[ERROR] [Executor] Exception in task 3.0 in stage 44.0 (TID 155)
[ERROR] [Executor] Exception in task 2.0 in stage 44.0 (TID 154)
[ERROR] [Executor] Exception in task 1.0 in stage 44.0 (TID 153)
[WARN] [TaskSetManager] Lost task 3.0 in stage 44.0 (TID 155, localhost): java.lang.StackOverflowError
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89)
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)

Any help, thanks.

**Comment by steven-haddix** [comment]
Did you resolve this?

**Comment by birdspring** [comment]
@steven-haddix  I solved this with the help of this page http://predictionio.incubator.apache.org/resources/faq/.
You can have a try.

**Comment by ebottabi** [comment]
@steven-haddix to resolve at this ""com.github.fommil.netlib" % "all" % "1.1.2" pomOnly()" to your dependencies if you are running on sbt.

**Comment by pferrel** [comment]
If this is required, how about a PR to change it for everyone?
